version: '3.4'

services:
  policemaps:
    image: ${DOCKER_REGISTRY-}policemaps
    build:
      context: .
      dockerfile: PoliceMaps/Dockerfile

  mapclient:
    image: mapclient
    ports:
      - "4200:80"

  sql:
    image: "mcr.microsoft.com/mssql/server"